"""create clinical_notes table

Revision ID: e42905241ed3
Revises:
Create Date: 2026-07-01 11:06:41.159884

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e42905241ed3"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clinical_notes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=100), nullable=False),
        sa.Column("clinician_id", sa.String(length=100), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_clinical_notes_clinician_id"),
        "clinical_notes",
        ["clinician_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_clinical_notes_patient_id"),
        "clinical_notes",
        ["patient_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_clinical_notes_patient_id"), table_name="clinical_notes")
    op.drop_index(op.f("ix_clinical_notes_clinician_id"), table_name="clinical_notes")
    op.drop_table("clinical_notes")
    # ### end Alembic commands ###
